### ISSUE TITLE
Login system

### ISSUE THREAD

**Issue by theodormoroianu** [TeamUnibuc/MDS#3] opened 2021-02-17 11:29 UTC

**Comment by felixp72** [comment] 2021-02-19 11:00
We can use PassportJS for authenticating users on different platforms. (http://www.passportjs.org/docs/downloads/html/)

For a smoother user experience, we should match accounts from social logins with the same email address and have only one account in our database

**Comment by felixp72** [comment] 2021-02-24 19:49
Duplicate of #31

**Closed as completed by felixp72** 2021-02-24 19:49 UTC
